
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    // Using process.env with fallback to ensure build succeeds even if env vars are missing
    // Vercel build step (prisma generate) needs a valid URL structure but doesn't connect
    url: process.env.DATABASE_URL ?? "postgresql://build:build@localhost:5432/build",
    directUrl: process.env.DIRECT_URL ?? "postgresql://build:build@localhost:5432/build",
  },
});
